name: Android Fastlane Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Java Home
        run: echo "JAVA_HOME is set to $JAVA_HOME"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.24.4'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
          working-directory: android
          
      - name: Clean Flutter build
        run: flutter clean

      - name: Build and distribute Android app
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
      
      